### ISSUE TITLE
Error: Cannot find module '/root/api/dist'

### ISSUE THREAD

**Issue by benclarkk** [crybapp/api#1]
Hi,
when running `npm start dev`,  I get this nice error: https://gist.github.com/benclarkk/82f000bcc3b15cfd352ee6f3bbcbbecf
here's my .env if you need it: https://gist.github.com/benclarkk/592a48fbad88c0722a632ffb619a7c5a
thank
\- ben

**Comment by williamsthing** [comment]
I think you're trying to run `npm run dev` - lmk if this helps!

**Comment by benclarkk** [comment]
ah yes, thanks!
