### ISSUE TITLE
Reduce logging in production mode

### ISSUE THREAD

**Issue by Simonx22** [crybapp/api#9]
Like the title is saying it'd be nice if we would reduce the logging of the API when in production mode. Right now it's logging pretty much everything like this: ``[CRYB-API-PRODUCTION] [WS] [RECIEVE] Opcode: 1, data: {}``

**Comment by JeDaYoshi** [comment]
This could be a good issue for new contributors to take.

**Comment by JeDaYoshi** [comment]
I actually reduced it. It'll only show that when it's not in production. Closing!
